export const WEATHER_CODES: Record<number, { label: string; icon: string }> = {
  113: { label: 'Sunny/Clear', icon: 'sun' },
  116: { label: 'Partly Cloudy', icon: 'cloud-sun' },
  119: { label: 'Cloudy', icon: 'cloud' },
  122: { label: 'Overcast', icon: 'cloud' },
  143: { label: 'Mist', icon: 'cloud-fog' },
  176: { label: 'Patchy Rain', icon: 'cloud-rain' },
  179: { label: 'Patchy Snow', icon: 'snowflake' },
  182: { label: 'Patchy Sleet', icon: 'cloud-hail' },
  185: { label: 'Patchy Freezing Drizzle', icon: 'cloud-hail' },
  200: { label: 'Thundery Outbreaks', icon: 'cloud-lightning' },
  227: { label: 'Blowing Snow', icon: 'snowflake' },
  230: { label: 'Blizzard', icon: 'snowflake' },
  248: { label: 'Fog', icon: 'cloud-fog' },
  260: { label: 'Freezing Fog', icon: 'cloud-fog' },
  263: { label: 'Patchy Light Drizzle', icon: 'cloud-drizzle' },
  266: { label: 'Light Drizzle', icon: 'cloud-drizzle' },
  281: { label: 'Freezing Drizzle', icon: 'cloud-hail' },
  284: { label: 'Heavy Freezing Drizzle', icon: 'cloud-hail' },
  293: { label: 'Patchy Light Rain', icon: 'cloud-rain' },
  296: { label: 'Light Rain', icon: 'cloud-rain' },
  299: { label: 'Moderate Rain at Times', icon: 'cloud-rain' },
  302: { label: 'Moderate Rain', icon: 'cloud-rain' },
  305: { label: 'Heavy Rain at Times', icon: 'cloud-rain' },
  308: { label: 'Heavy Rain', icon: 'cloud-rain' },
  311: { label: 'Light Freezing Rain', icon: 'cloud-hail' },
  314: { label: 'Moderate/Heavy Freezing Rain', icon: 'cloud-hail' },
  317: { label: 'Light Sleet', icon: 'cloud-hail' },
  320: { label: 'Moderate/Heavy Sleet', icon: 'cloud-hail' },
  323: { label: 'Patchy Light Snow', icon: 'snowflake' },
  326: { label: 'Light Snow', icon: 'snowflake' },
  329: { label: 'Patchy Moderate Snow', icon: 'snowflake' },
  332: { label: 'Moderate Snow', icon: 'snowflake' },
  335: { label: 'Patchy Heavy Snow', icon: 'snowflake' },
  338: { label: 'Heavy Snow', icon: 'snowflake' },
  350: { label: 'Ice Pellets', icon: 'cloud-hail' },
  353: { label: 'Light Rain Shower', icon: 'cloud-rain' },
  356: { label: 'Moderate/Heavy Rain Shower', icon: 'cloud-rain' },
  359: { label: 'Torrential Rain Shower', icon: 'cloud-rain' },
  362: { label: 'Light Sleet Showers', icon: 'cloud-hail' },
  365: { label: 'Moderate/Heavy Sleet Showers', icon: 'cloud-hail' },
  368: { label: 'Light Snow Showers', icon: 'snowflake' },
  371: { label: 'Moderate/Heavy Snow Showers', icon: 'snowflake' },
  374: { label: 'Light Showers of Ice Pellets', icon: 'cloud-hail' },
  377: { label: 'Moderate/Heavy Showers of Ice Pellets', icon: 'cloud-hail' },
  386: { label: 'Patchy Light Rain with Thunder', icon: 'cloud-lightning' },
  389: { label: 'Moderate/Heavy Rain with Thunder', icon: 'cloud-lightning' },
  392: { label: 'Patchy Light Snow with Thunder', icon: 'cloud-lightning' },
  395: { label: 'Moderate/Heavy Snow with Thunder', icon: 'cloud-lightning' },
};

export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Spanish' },
  { code: 'fr', name: 'French' },
  { code: 'de', name: 'German' },
  { code: 'it', name: 'Italian' },
  { code: 'pt', name: 'Portuguese' },
  { code: 'ru', name: 'Russian' },
  { code: 'zh', name: 'Chinese' },
  { code: 'ja', name: 'Japanese' },
  { code: 'ar', name: 'Arabic' },
];

export const UNITS = [
  { code: 'm', name: 'Metric (°C, km/h)', symbol: '°C' },
  { code: 's', name: 'Scientific (K, m/s)', symbol: 'K' },
  { code: 'f', name: 'Fahrenheit (°F, mph)', symbol: '°F' },
];

export const TABS = [
  { id: 'current', name: 'Current', icon: 'thermometer' },
  { id: 'forecast', name: 'Forecast', icon: 'calendar' },
  { id: 'historical', name: 'Historical', icon: 'history' },
  { id: 'marine', name: 'Marine', icon: 'waves' },
];
